### ISSUE TITLE
Why are things required to be `Sync`?

### ISSUE THREAD

**Issue by thomaseizinger** [khuey/lazy-init#10]
Could you elaborate why the type arguments need to be `Sync`?

Can you not rely on the compiler to infer for you whether or not `Lazy<T>` is `Sync` depending on whether or not `T` is `Sync`?

I want to lazily create a `Future` and futures are not `Sync` since they take `&mut self`.

**Comment by bonzini** [comment]
Compiler inference is not possible for `LazyTransform<T, U>` because `UnsafeCell` is not Sync. However indeed the requirement for T and U to be Sync is unnecessary. Both of these should be okay:

```rust
        let rc = Rc::new(true);
        let lazy: Lazy<Rc<bool>> = Lazy::new();
        assert_eq!(Rc::strong_count(&rc), 1);
        lazy.get_or_create(|| rc.clone());
        assert_eq!(Rc::strong_count(&rc), 2);
```

```rust
        let cell = Cell::new(21u8);
        let lazy: LazyTransform<Cell<u8>, u8> = LazyTransform::new(cell);
        lazy.get_or_create(|cell| cell.get());
        assert_eq!(lazy.get(), Some(&21));
```
