### ISSUE TITLE
Tests will start to panic in new rust version due to use of outdated crossbeam

### ISSUE THREAD

**Issue by 5225225** [khuey/lazy-init#20]
Hello! I'm coming to this repo from https://github.com/rust-lang/rust/pull/99389, where the checks for mem::uninitialized are being made stricter.

This crate doesn't seem to have any direct issues, but it uses scoped-pool as a dev dependency, which doesn't look to have been updated in a good few years. Would be worth looking to see if modern crossbeam has the functionality you need from scoped-pool.

**Comment by khuey** [comment]
Alright I switched to using rayon.
