### ISSUE TITLE
soundness hole with types that are Sync + !Send

### ISSUE THREAD

**Issue by niklasf** [khuey/lazy-init#9]
Hi, I believe that the `unsafe impl Sync` needs to also require Send. Otherwise it is possible to transfer non-Send values between threads.

Similar issues in other crates:
* https://github.com/indiv0/lazycell/issues/67
* https://github.com/niklasf/double-checked-cell/commit/ee6b6f3b94bf50bb52daedc8da6888ba33704a26

```rust
// make a type that is Sync but not Send
// such types are arguably very rare
#![feature(optin_builtin_traits)]
#[derive(Debug)]
struct Foo(u32);
impl !Send for Foo { }

fn should_fail_to_compile() {
    let lazy = Lazy::new();

    let pool = Pool::new(1);
    pool.scoped(|scope| {
        let l = &lazy;
        scope.execute(move || {
            // we transfer a value from this thread ...
            l.get_or_create(|| Foo(42));
        });
    });

    // ... to another thread
    let result = lazy.into_inner();
    println!("{:?}", result);
}
```

**Comment by khuey** [comment]
I need to think about this a bit more but I believe you're correct.

**Comment by niklasf** [comment]
Any news? I see 66bbfc250cf6f277e4343440abff6fad1eb1df2a, but I believe `U` requires the same bound. For example the snippet above still compiles.

**Comment by matklad** [comment]
+1

This is unsound, it's better to fix the issue and yank old releases ;)
